# This workflow will do a clean install of node dependencies and run tests on node version 14.x

name: Affirmations CI

on:
  push:
    branches: [ * ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Installing dependencies
        run: npm ci
      - name: Running tests
        run: npm test
        env:
          CI: true
